### ISSUE TITLE
page : ayush jain is not loading 

### ISSUE THREAD

**Issue by Ultimecia1463** [Ultimecia1463/GTM#19]
![image](https://github.com/user-attachments/assets/1b986674-8d6c-4ba5-8505-5ec8a5b45536)

**Comment by Ultimecia1463** [comment]
@ayujain1714 look into this

**Comment by ayujain1714** [comment]
Sorry, but the project was created using React. That can not be directly linked by using index.html reference link.
To resolve the issue I am using a predeployed link at that point.
